<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Almostengr.OpenDataMontgomeryAlGov.ApiClient.Web-52865659-3f40-4f6b-ac60-780c366aaa7b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Almostengr.OpenDataMontgomeryAlGov.ApiClient\Almostengr.OpenDataMontgomeryAlGov.ApiClient.csproj" />
  </ItemGroup>

</Project>
